//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShowAllOrdersDetail
    {
        public int UserId { get; set; }
        public int ManufacturerID { get; set; }
        public int ModelId { get; set; }
        public int CarId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ManufacturerName { get; set; }
        public string ModelName { get; set; }
        public string ModelImageName { get; set; }
        public System.DateTime StartRentalDate { get; set; }
        public System.DateTime EndRentalDate { get; set; }
        public decimal TotalRentalCost { get; set; }
        public int OrderID { get; set; }
        public System.DateTime OrderDate { get; set; }
    }
}
